04 lection2 01 histogram
js-tasks-ru/htmlcss-20220414_lancov-r pull request #14
Opened 2022-04-27 20:38 UTC by RomanLantsov

2022-05-03 21:26 UTC, GSemikozov requested changes

2022-05-03 21:26 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 185px;
лишнее

2022-05-03 21:26 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    border: 1px solid #ACB5BD
цвета проставим из css-переменных

2022-05-03 21:26 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__p {
вместо p может поставить любой другой тег - и тогда придется менять класс. Поэтому - лучше более семантический класс, например .histogram__text

2022-05-03 21:26 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 24px;
лишнее

2022-05-03 21:26 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__h4 {
тут та же истории (.histogram__title?)

2022-05-03 21:26 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.filter {
класс вне БЭМ

2022-05-03 21:26 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin-top: 40px;
39

2022-05-03 21:26 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +     display: flex;
тут неплохо бы зафиксировать высоту (50px по дизайну), чтобы высота дочерних элементов указывалась в процентах

2022-05-03 21:26 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 1px;
лишнее

2022-05-04 09:48 UTC, RomanLantsov commented on 04-lection2/01-histogram/histogram.css
> +    height: 185px;
совсем без height histogram__chart схлопнится...
Ты вроде говорил что высота фиксированая. 
Я на height:100% заменил пока, чтобы тянулось и по высоте и зависило от высоты родителя.   Или меня вообще не туда понесло?

2022-05-04 09:48 UTC, RomanLantsov commented on 04-lection2/01-histogram/histogram.css
> +    border: 1px solid #ACB5BD
исправился

2022-05-04 09:52 UTC, RomanLantsov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__h4 {
исправил

2022-05-04 09:52 UTC, RomanLantsov commented on 04-lection2/01-histogram/histogram.css
> +.filter {
упс!)  Исправился

2022-05-04 10:01 UTC, RomanLantsov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__p {
теперь понял почему. Исправлено

2022-05-04 10:01 UTC, RomanLantsov commented on 04-lection2/01-histogram/histogram.css
> +    height: 24px;
исправлено

2022-05-04 10:04 UTC, RomanLantsov commented on 04-lection2/01-histogram/histogram.css
> +    height: 185px;
Тут понял почему.  Убрал. Теперь Высота histogram__chart фиксируется в сомом histogram__chart

2022-05-04 10:04 UTC, RomanLantsov commented on 04-lection2/01-histogram/histogram.css
> +    margin-top: 40px;
оооок..   исправил!

2022-05-04 10:05 UTC, RomanLantsov commented on 04-lection2/01-histogram/histogram.css
> +     display: flex;
Иии... Да! Исправлено. теперь общая высота не нужна. Так гибче.
Спасибо)!

2022-05-04 10:07 UTC, RomanLantsov commented on 04-lection2/01-histogram/histogram.css
> +    height: 1px;
Почему-то без этого чарт не тянулся..  убрал, сейчас всё ок.

2022-05-05 08:01 UTC, GSemikozov requested changes

2022-05-05 08:01 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +            <p class="filter">
а вот здесь filter осталось)
+ это не `p` а `a` = ссылка

2022-05-05 16:05 UTC, RomanLantsov commented on 04-lection2/01-histogram/index.html
> +            <p class="filter">
мой косяк)
Поправил имя класса.
Заменил на ссылку

2022-05-06 20:29 UTC, GSemikozov approved these changes

2022-05-06 20:29 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-05-06 20:30 UTC, GSemikozov approved these changes

2022-05-06 20:30 UTC, merged