05 lection3 01 tooltip
js-tasks-ru/htmlcss-20220414_lancov-r pull request #16
Opened 2022-04-27 20:39 UTC by RomanLantsov

2022-05-03 21:29 UTC, GSemikozov requested changes

2022-05-03 21:29 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +  height: 24px;
лишнее

2022-05-03 21:29 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +  background: #212429;
цвета из css-переменных

2022-05-05 16:13 UTC, RomanLantsov commented on 05-lection3/01-tooltip/tooltip.css
> +  height: 24px;
пофиксил

2022-05-05 16:13 UTC, RomanLantsov commented on 05-lection3/01-tooltip/tooltip.css
> +  background: #212429;
и тут пофиксил

2022-05-06 20:28 UTC, GSemikozov approved these changes

2022-05-06 20:29 UTC, merged