05 lection3 02 modal
js-tasks-ru/htmlcss-20220414_lancov-r pull request #17
Opened 2022-04-27 20:39 UTC by RomanLantsov

2022-04-27 20:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-27 20:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-27 20:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-03 21:32 UTC, GSemikozov requested changes

2022-05-03 21:32 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__back {
лишний элемент, позиционировании и полупрозрачный фон задаем на .modal (причем - fixed + фон через rgba)

2022-05-03 21:32 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  margin: 10px 10.33px 0;
дробные пиксели лучше не использовать

2022-05-03 21:32 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  height: 193px;
51-54 строки просто удалить, так не надо)

2022-05-03 21:32 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.view {
что-то лишнее затесалось в стили компонента

2022-05-04 19:34 UTC, RomanLantsov commented on 05-lection3/02-modal/modal.css
> +.view {
упс)

2022-05-04 19:35 UTC, RomanLantsov commented on 05-lection3/02-modal/modal.css
> +  height: 193px;
понял, убрал

2022-05-04 19:35 UTC, RomanLantsov commented on 05-lection3/02-modal/modal.css
> +  margin: 10px 10.33px 0;
поравил

2022-05-04 19:41 UTC, RomanLantsov commented on 05-lection3/02-modal/modal.css
> +.modal__back {
перенес, фон заменил

2022-05-06 20:30 UTC, GSemikozov requested changes

2022-05-06 20:30 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  margin: 0 0 14px 40px;
вместо марджинов на уровне каждого дочернего элемента чтобы оттолкнуться от границ блока - лучше вместо этого на уровне блока задать общие паддинги

2022-05-09 11:21 UTC, RomanLantsov commented on 05-lection3/02-modal/modal.css
> +  margin: 0 0 14px 40px;
Готово! 
Крест - position: absolute и всем одинаковые паддинги.

2022-05-10 20:24 UTC, GSemikozov approved these changes

2022-05-10 20:24 UTC, merged